language: python
python:
    - '2.6'
    - '2.7'
    - '3.5'
install:
    - wget http://www.antlr.org/download/antlr-4.7-complete.jar
    - pip install --upgrade pip pytest coverage codecov
    - pip install -v .[dev]
script:
    - coverage run --source umdpfmt -m py.test
after_success:
    - codecov
# deploy:
#   provider: pypi
#   user:
#   password:
#     secure: 
#   on:
#     tags: true
#     repo: ScottWales/umdpfmt
#   distributions: "sdist bdist_wheel"
